source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '8.0'

target 'MJCalendar_Example' do
  pod "MJCalendar", :path => "../"
  pod 'HexColors', '~> 2.3'
end

target 'MJCalendar_Tests' do
    pod "MJCalendar", :path => "../"
end
