source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MJCalendar_Example', :exclusive => true do
  pod "MJCalendar", :path => "../"
  pod 'HexColors', '~> 2.3'
end

target 'MJCalendar_Tests', :exclusive => true do
  pod "MJCalendar", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
